development:
  adapter: mysql
  encoding: utf8
  host: 140.254.80.125
  database: gisbank
  pool: 5
  username: gisman
  password: gisman$

test:
  adapter: mysql
  encoding: utf8
  host: 140.254.80.125
  database: gisbank
  pool: 5
  username: gisman
  password: gisman$

production:
  adapter: mysql
  encoding: utf8
  host: 140.254.80.125
  database: gisbank
  pool: 5
  username: gisman
  password: gisman$
