development:
  adapter: mysql
  encoding: utf8
  database: gisbank
  pool: 5
  username: gisbank
  password: gisbank

test:
  adapter: mysql
  encoding: utf8
  database: gisbank
  pool: 5
  username: gisbank
  password: gisbank

production:
  adapter: mysql
  encoding: utf8
  database: gisbank
  pool: 5
  username: gisbank
  password: gisbank
