development:
  adapter: mysql
  encoding: utf8
  host: 127.0.0.1
  database: gisbank
  pool: 5
  username: root
  password:

#development:
#  adapter: mysql
#  encoding: utf8
#  host: 140.254.80.125
#  database: gisbank
#  pool: 5
#  username: gisman
#  password: gisman$

#development:
#  adapter: sqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000

#development:
#  adapter: mysql
#  encoding: utf8
#  host: localhost
#  database: gisbank
#  pool: 5
#  username: root
#  password: password

test:
  adapter: mysql
  encoding: utf8
  host: 127.0.0.1
  database: gisbank
  pool: 5
  username: root
  password:

production:
  adapter: mysql
  encoding: utf8
  host: xio29.osc.edu
  database: gisbank
  pool: 5
  username: supramap_admin
  password: nosnoraA

